import type { Preferences, PreferencesType } from "../utils";

const links: Record<
	Exclude<
		"GramIO" | PreferencesType["linter"] | PreferencesType["others"][0],
		"None"
	>,
	string
> = {
	GramIO: "[GramIO](https://gramio.netlify.app/)",
	ESLint: "[ESLint](https://eslint.org/)",
	Biome: "[Biome](https://biomejs.dev/)",
	Husky: "[Husky](https://typicode.github.io/husky/)",
};

export function getReadme({ dir, linter, others }: Preferences) {
	const stack = [];

	stack.push(`- Telegram Bot API framework - ${links.GramIO}`);
	if (linter !== "None") stack.push(`- Linter - ${links[linter]}`);
	if (others.length)
		stack.push(`- Others tools - ${others.map((x) => links[x]).join(", ")}`);

	return [
		`# ${dir}`,
		"",
		"This template autogenerated by [create-gramio](https://github.com/gramiojs/create-gramio)",
		"",
		"### Stack",
		...stack,
	].join("\n");
}
